//
//  ICPField.h
//  IBMCaptureSDK
//
//  Copyright (c) 2015 IBM Corporation. All rights reserved.
//

#import "ICPObject.h"

@protocol ICPCharacter;
/**

 The ICPField protocol represents a piece of information with a type and a value. It can be attached to batches, documents,
 pages, or other fields.

 @see ICPBatch
 @see ICPDocument
 @see ICPPage
 */
@protocol ICPField <ICPObject>

/** The value of the field. */
@property (nonatomic, strong) id value;

/** The ICPCharacters recognised by OCR */
@property (nonatomic, strong) NSArray *characters;

/**
 Notify field that it has been changed manually so information generated by OCR must be removed as it is no longer valid
 */
- (void)reset;

@end
